[package]
name = "NGLBomber"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "multipart", "stream"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }

